# Generated by Django 4.1.1 on 2022-10-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='verified_artist',
            new_name='verified_speaker',
        ),
    ]
