# Generated by Django 4.1.1 on 2022-10-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_verified_artist_speaker_verified_speaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='topic',
            field=models.TextField(max_length=250),
        ),
    ]
