# Generated by Django 4.1.1 on 2022-10-06 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_speaker_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150)),
                ('duration', models.IntegerField(default=0)),
                ('livestream', models.IntegerField(default=0)),
                ('speakers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main_app.speaker')),
            ],
        ),
    ]
