# Generated by Django 4.1.1 on 2022-10-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='livestream',
            field=models.BooleanField(default=False),
        ),
    ]
