# Generated by Django 4.1.1 on 2022-10-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_event_tour_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150)),
                ('tour_date', models.CharField(default='TBD', max_length=150)),
                ('events', models.ManyToManyField(to='main_app.event')),
            ],
        ),
    ]
