# Generated by Django 4.1.1 on 2022-10-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_tour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='location',
            new_name='tour_name',
        ),
    ]
